package:
  name: backports
  version: 1.0

build:
  number: 4
  noarch: python
  script:
    - cd {{ SP_DIR if SP_DIR is defined else '' }}
    - mkdir -p backports
    - cp {{ RECIPE_DIR }}/init.py backports/__init__.py

requirements:
  build:
    - python >=3
  run:
    - python >=3

test:
  requires:
    - pip
  commands:
    - unset PIP_NO_INDEX                      # [unix]
    - set "PIP_NO_INDEX="                     # [win]
    - python -m pip install --target alt-site backports.tarfile
    - export PYTHONPATH="${SP_DIR}:alt-site"  # [unix]
    - set "PYTHONPATH=%SP_DIR%;alt-site"      # [win]
    - python -c "import backports.tarfile"

about:
  home: http://github.com/conda-forge/backports-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A package to ensure the `backports` namespace is available.

extra:
  recipe-maintainers:
    - jakirkham
    - isuruf
