package:
  name: backports
  version: 1.0

build:
  number: 4
  noarch: python
  script:
    - cd {{ SP_DIR if SP_DIR is defined else '' }}
    - mkdir -p backports
    - echo "__path__ = __import__('pkgutil').extend_path(__path__, __name__)" > backports/__init__.py

requirements:
  build:
    - python >=2.7
  run:
    - python >=2.7

test:
  requires:
    - backports.zoneinfo
    - python 3.8
    - setuptools 71.0.4
  imports:
    - backports
    - backports.zoneinfo
    - setuptools

about:
  home: http://github.com/conda-forge/backports-feedstock
  license: BSD-3-Clause
  license_file: {{ RECIPE_DIR if RECIPE_DIR is defined else '' }}/LICENSE.txt
  summary: A package to ensure the `backports` namespace is available.

extra:
  recipe-maintainers:
    - jakirkham
